package de.idrinth.waraddonclient.gui;

import darrylbu.util.MenuScroller;
import de.idrinth.waraddonclient.service.Config;
import de.idrinth.waraddonclient.model.addon.Addon;
import de.idrinth.waraddonclient.model.GuiAddonList;
import de.idrinth.waraddonclient.model.addon.ActualAddon;
import de.idrinth.waraddonclient.model.addon.NoAddon;
import de.idrinth.waraddonclient.service.Backup;
import de.idrinth.waraddonclient.service.ProgressReporter;
import javax.swing.table.TableRowSorter;
import de.idrinth.waraddonclient.service.logger.BaseLogger;
import de.idrinth.waraddonclient.service.Shedule;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.io.Serializable;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicReference;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JEditorPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.ListSelectionModel;
import javax.swing.ScrollPaneConstants;
import javax.swing.WindowConstants;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

public class Addons extends BaseFrame implements MainWindow, Serializable {

    private static Addon activeAddon = new NoAddon();

    private final AtomicReference<GuiAddonList> addonList = new AtomicReference<>();

    private final AtomicReference<BaseLogger> logger = new AtomicReference<>();

    private final AtomicReference<Config> config = new AtomicReference<>();

    private final AtomicReference<ProgressReporter> reporter = new AtomicReference<>();
    
    private final MainWindowMap map;

    private final AtomicReference<Backup> backup = new AtomicReference<>();

    public Addons(MainWindowMap map, GuiAddonList addonList, BaseLogger logger, Shedule schedule, Config config, ProgressReporter reporter, Backup backup) {
        super(config);
        this.map = map;
        this.addonList.set(addonList);
        this.logger.set(logger);
        this.config.set(config);
        this.reporter.set(reporter);
        this.backup.set(backup);
        initComponents();
        finishGuiBuilding(schedule);
    }

    private void finishGuiBuilding(Shedule schedule) {
        addonListTable.getSelectionModel().addListSelectionListener(new TableListener());
        addonListTable.setRowSorter(new TableRowSorter<>(addonListTable.getModel()));
        addonList.get().setModel((DefaultTableModel) addonListTable.getModel());
        description.addHyperlinkListener(new HyperlinkListenerImpl());
        addonList.get().setMenu(menuTags, (java.awt.event.ActionEvent evt) -> newFilter());
        schedule.register(300, addonList.get());
        MenuScroller.setScrollerFor(menuTags);
        (new TableListener()).updateUi();
    }

    private void newFilter() {
        try {
            TextCategory rf = new TextCategory(inputSearch.getText(), this.addonList.get());
            ((TableRowSorter) addonListTable.getRowSorter()).setRowFilter(rf);
        } catch (java.util.regex.PatternSyntaxException exception) {
            logger.get().error(exception);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JSplitPane base = new JSplitPane();
        JPanel leftSide = new JPanel();
        inputSearch = new JTextField();
        JScrollPane scroll = new JScrollPane();
        addonListTable = new JTable();
        JButton buttonDeleteSearch = new JButton();
        JButton buttonUpdateAll = new JButton();
        rightSide = new JTabbedPane();
        JPanel tabMain = new JPanel();
        JScrollPane scrollDescription = new JScrollPane();
        description = new JEditorPane();
        installButton = new JButton();
        removeButton = new JButton();
        addonTitle = new JLabel();
        currentTags = new JLabel();
        JPanel tabSettings = new JPanel();
        JScrollPane scrollSettings = new JScrollPane();
        uploadReason = new JTextArea();
        uploadUrl = new JTextField();
        JLabel uploadLabel = new JLabel();
        uploadEnable = new JCheckBox();
        uploadFile = new JTextField();
        JLabel uploadFileLabel = new JLabel();
        JMenuBar mainMenu = new JMenuBar();
        menuTags = new JMenu();

        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        base.setDividerLocation(350);
        base.setToolTipText("");
        base.setMinimumSize(new Dimension(300, 200));
        base.setName(""); // NOI18N

        inputSearch.addActionListener(this::inputSearchActionPerformed);
        inputSearch.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent evt) {
                inputSearchKeyReleased(evt);
            }
        });

        scroll.setMaximumSize(null);

        addonListTable.setAutoCreateRowSorter(true);
        addonListTable.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Status", "Name", "Version", "Installed", "Endorsements", "Downloads"
            }
        ) {
            Class[] types = new Class [] {
                String.class, String.class, String.class, String.class, Integer.class, Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        addonListTable.setColumnSelectionAllowed(true);
        addonListTable.setMaximumSize(null);
        addonListTable.setName(""); // NOI18N
        addonListTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        scroll.setViewportView(addonListTable);
        addonListTable.getColumnModel().getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        buttonDeleteSearch.setText("X");
        buttonDeleteSearch.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                buttonDeleteSearchMouseClicked(evt);
            }
        });

        buttonUpdateAll.setText("Update All");
        buttonUpdateAll.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                buttonUpdateAllMouseClicked(evt);
            }
        });

        GroupLayout leftSideLayout = new GroupLayout(leftSide);
        leftSide.setLayout(leftSideLayout);
        leftSideLayout.setHorizontalGroup(leftSideLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(leftSideLayout.createSequentialGroup()
                .addGroup(leftSideLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(leftSideLayout.createSequentialGroup()
                        .addComponent(inputSearch, GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDeleteSearch)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonUpdateAll))
                    .addComponent(scroll, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        leftSideLayout.setVerticalGroup(leftSideLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(leftSideLayout.createSequentialGroup()
                .addGroup(leftSideLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(inputSearch, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDeleteSearch)
                    .addComponent(buttonUpdateAll))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addContainerGap())
        );

        base.setLeftComponent(leftSide);

        scrollDescription.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollDescription.setMaximumSize(null);

        description.setEditable(false);
        description.setContentType("text/html"); // NOI18N
        scrollDescription.setViewportView(description);

        installButton.setText("(Re)Install");
        installButton.addActionListener(this::installButtonActionPerformed);

        removeButton.setText("Remove");
        removeButton.addActionListener(this::removeButtonActionPerformed);

        addonTitle.setFont(new Font("Tahoma", 1, 11)); // NOI18N

        GroupLayout tabMainLayout = new GroupLayout(tabMain);
        tabMain.setLayout(tabMainLayout);
        tabMainLayout.setHorizontalGroup(tabMainLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(tabMainLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(currentTags, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(scrollDescription, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(tabMainLayout.createSequentialGroup()
                .addComponent(installButton)
                .addGap(42, 42, 42)
                .addComponent(addonTitle, GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addComponent(removeButton)
                .addContainerGap())
        );
        tabMainLayout.setVerticalGroup(tabMainLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(tabMainLayout.createSequentialGroup()
                .addGroup(tabMainLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(removeButton)
                    .addComponent(installButton)
                    .addComponent(addonTitle))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollDescription, GroupLayout.PREFERRED_SIZE, 360, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentTags)
                .addGap(26, 26, 26))
        );

        rightSide.addTab("Main", tabMain);

        uploadReason.setEditable(false);
        uploadReason.setColumns(20);
        uploadReason.setRows(5);
        scrollSettings.setViewportView(uploadReason);

        uploadUrl.setEditable(false);
        uploadUrl.setToolTipText("");

        uploadLabel.setText("Upload URL");

        uploadEnable.setText("Allow Upload");
        uploadEnable.addActionListener(this::uploadEnableActionPerformed);

        uploadFile.setEditable(false);
        uploadFile.setToolTipText("");

        uploadFileLabel.setText("Upload File");

        GroupLayout tabSettingsLayout = new GroupLayout(tabSettings);
        tabSettings.setLayout(tabSettingsLayout);
        tabSettingsLayout.setHorizontalGroup(tabSettingsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(tabSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabSettingsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(tabSettingsLayout.createSequentialGroup()
                        .addComponent(uploadEnable)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(tabSettingsLayout.createSequentialGroup()
                        .addComponent(uploadLabel, GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(uploadUrl, GroupLayout.PREFERRED_SIZE, 265, GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabSettingsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(uploadFile, GroupLayout.PREFERRED_SIZE, 265, GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollSettings, GroupLayout.Alignment.TRAILING)))
            .addGroup(tabSettingsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(tabSettingsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(uploadFileLabel, GroupLayout.PREFERRED_SIZE, 189, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(344, Short.MAX_VALUE)))
        );
        tabSettingsLayout.setVerticalGroup(tabSettingsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(tabSettingsLayout.createSequentialGroup()
                .addComponent(scrollSettings, GroupLayout.PREFERRED_SIZE, 247, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabSettingsLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(uploadUrl, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(uploadLabel, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(uploadFile, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uploadEnable)
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(tabSettingsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(GroupLayout.Alignment.TRAILING, tabSettingsLayout.createSequentialGroup()
                    .addContainerGap(278, Short.MAX_VALUE)
                    .addComponent(uploadFileLabel, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
                    .addGap(92, 92, 92)))
        );

        rightSide.addTab("Settings", tabSettings);

        base.setRightComponent(rightSide);

        menuTags.setText("Tags");
        menuTags.setMaximumSize(new Dimension(40, 22));
        mainMenu.add(menuTags);

        setJMenuBar(mainMenu);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(base, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(base, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * the searchtext was changed
     *
     * @param evt
     */
    private void inputSearchActionPerformed(ActionEvent evt) {//GEN-FIRST:event_inputSearchActionPerformed
        newFilter();
    }//GEN-LAST:event_inputSearchActionPerformed

    /**
     * the searchtext was changed
     *
     * @param evt
     */
    private void inputSearchKeyReleased(KeyEvent evt) {//GEN-FIRST:event_inputSearchKeyReleased
        newFilter();
    }//GEN-LAST:event_inputSearchKeyReleased

    /**
     *
     * @param evt
     */
    private void uploadEnableActionPerformed(ActionEvent evt) {//GEN-FIRST:event_uploadEnableActionPerformed
        config.get().setEnabled(activeAddon.getName(), uploadEnable.isSelected());
    }//GEN-LAST:event_uploadEnableActionPerformed

    private void buttonDeleteSearchMouseClicked(MouseEvent evt) {//GEN-FIRST:event_buttonDeleteSearchMouseClicked
        inputSearch.setText("");
        inputSearchActionPerformed(new java.awt.event.ActionEvent(evt.getSource(), 1001, "reset"));
    }//GEN-LAST:event_buttonDeleteSearchMouseClicked

    private void buttonUpdateAllMouseClicked(MouseEvent evt) {//GEN-FIRST:event_buttonUpdateAllMouseClicked
        Integer choice = config.get().getAutoBackupOnUpdateAll();
        if (choice == 2) {//cancel or unset
            choice = JOptionPane.showConfirmDialog(this, "Do you want to make a backup first?");
        }
        if (choice == 2) {//cancel or unset
            return;
        }
        reporter.get().start(choice == 0 ? "Backup & Update All" : "Updating All", () -> {
            this.setEnabled(true);
            this.updateList();
        });
        Executor exe = Executors.newSingleThreadExecutor();
        exe.execute(() -> {
            this.setEnabled(false);
            reporter.get().incrementMax(addonList.get().size());
        });
        if (choice == 0) {//yes          
            exe.execute(() -> {
                try {
                    backup.get().create(reporter.get());
                } catch (IOException ex) {
                    logger.get().error(ex);
                }
            });
        }
        exe.execute(() -> {
            for (int i = 0; i < addonList.get().size(); i++) {
                Addon addon = addonList.get().get(i);
                if (addon.getStatus().equals("X")) {
                    addon.install(reporter.get());
                }
                reporter.get().incrementCurrent();
            }
            reporter.get().stop();
        });
    }//GEN-LAST:event_buttonUpdateAllMouseClicked

    /**
     * delete addon was clicked
     *
     * @param evt
     */
    private void removeButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        reporter.get().start("Removing " + activeAddon.getName(), () -> {
            this.setEnabled(true);
            this.updateList();
        });
        this.setEnabled(false);
        activeAddon.uninstall(reporter.get());
        reporter.get().stop();
    }//GEN-LAST:event_removeButtonActionPerformed

    /**
     * The button install was clicked
     *
     * @param evt
     */
    private void installButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_installButtonActionPerformed
        reporter.get().start("Installing " + activeAddon.getName(), () -> {
            this.setEnabled(true);
            this.updateList();
        });
        this.setEnabled(false);
        activeAddon.install(reporter.get());
        reporter.get().stop();
    }//GEN-LAST:event_installButtonActionPerformed

    private void formWindowClosing(WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        map.exchange(MainWindowMap.ADDONS, MainWindowMap.START);
    }//GEN-LAST:event_formWindowClosing

    /**
     * updates addon list
     */
    private void updateList() {
        for (int position = addonListTable.getRowCount() -1 ; position >= 0 ; position--) {
            Addon addon = addonList.get().get(addonListTable.convertRowIndexToModel(position));
            if (addon.getInstalled().equals("-") && addon.getStatus().equals("?")) {
                ((DefaultTableModel) addonListTable.getModel()).removeRow(position);
                continue;
            }
            addonListTable.setValueAt(addon.getStatus(), position, 0);
            addonListTable.setValueAt(addon.getName(), position, 1);
            addonListTable.setValueAt(addon.getVersion(), position, 2);
            addonListTable.setValueAt(addon.getInstalled(), position, 3);
            addonListTable.setValueAt(addon.getEndorsements(), position, 4);
            addonListTable.setValueAt(addon.getDownloads(), position, 5);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JTable addonListTable;
    private JLabel addonTitle;
    private JLabel currentTags;
    private JEditorPane description;
    private JTextField inputSearch;
    private JButton installButton;
    private JMenu menuTags;
    private JButton removeButton;
    private JTabbedPane rightSide;
    private JCheckBox uploadEnable;
    private JTextField uploadFile;
    private JTextArea uploadReason;
    private JTextField uploadUrl;
    // End of variables declaration//GEN-END:variables

    private class HyperlinkListenerImpl implements HyperlinkListener {

        @Override
        public void hyperlinkUpdate(HyperlinkEvent event) {
            if (HyperlinkEvent.EventType.ACTIVATED.equals(event.getEventType())) {
                try {
                    Desktop.getDesktop().browse(event.getURL().toURI());
                } catch (java.net.URISyntaxException | java.io.IOException exception) {
                    logger.get().error(exception);
                }
            }

        }
    }

    private class TableListener implements ListSelectionListener {

        @Override
        public void valueChanged(ListSelectionEvent event) {
            try {
                int row = addonListTable.getSelectedRow();
                if (row != -1) {
                    activeAddon = addonList.get().get(addonListTable.convertRowIndexToModel(row));
                }
            } catch (java.lang.ArrayIndexOutOfBoundsException exception) {
                logger.get().error(exception);
                return;
            }
            if (activeAddon == null) {
                return;
            }
            updateUi();
        }

        /**
         * Updates the ui to show the current addon's data
         */
        public void updateUi() {
            if (activeAddon == null) {
                return;
            }
            description.setText(activeAddon.getDescription(config.get().getLanguage()));
            if (activeAddon instanceof ActualAddon) {
                new Thread(((ActualAddon) activeAddon).loadDescription(description, config.get().getLanguage())).start();
            }
            addonTitle.setText(activeAddon.getName());
            installButton.setEnabled(true);
            removeButton.setEnabled(true);
            rightSide.setEnabledAt(1, false);
            setTitle(activeAddon.getName());
            rightSide.setEnabledAt(1, activeAddon.showSettings());
            uploadReason.setText(activeAddon.getReason());
            uploadUrl.setText(activeAddon.getUrl());
            uploadFile.setText(activeAddon.getFile());
            uploadEnable.setSelected(config.get().isEnabled(activeAddon.getName()));
            String taglist = "Tagged: ";
            taglist = activeAddon.getTags().stream().map(tagname -> tagname + ", ").reduce(taglist, String::concat);
            currentTags.setText(taglist.substring(0, taglist.length() - 2));
        }
    }
}
