package de.idrinth.waraddonclient.gui;

import de.idrinth.waraddonclient.Utils;
import de.idrinth.waraddonclient.service.Config;
import de.idrinth.waraddonclient.service.Request;
import java.io.IOException;
import java.net.URISyntaxException;
import de.idrinth.waraddonclient.service.logger.BaseLogger;
import de.idrinth.waraddonclient.service.Restarter;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JEditorPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

public class Start extends BaseFrame implements MainWindow
{
    private final BaseLogger logger;
    
    private final Restarter restarter;

    private final MainWindowMap map;

    public Start(MainWindowMap map, BaseLogger logger, Config config, Restarter restarter, Request client) {
        super(config);
        this.map = map;
        this.restarter = restarter;
        this.logger = logger;
        initComponents();
        setTitle("Start");
        welcome.setText("<html><h1>Welcome to the Warhammer Online Addon Client!</h1><p>You are running version <b>"+config.getVersion()+"</b>.</p><br/><p>Choose the tool to use below!</p>");
        new Thread(() -> {
            Utils.sleep(1000, logger);//This fixes a weird bug
            welcome.setText("<html><h1>Welcome to the Warhammer Online Addon Client!</h1><p>You are running version <b>"+config.getVersion()+"</b>.</p><p>The current Version is <b>"+client.getVersion()+"</b>.</p><br/><p>Choose the tool to use below!</p>");
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JButton addons = new JButton();
        JButton settings = new JButton();
        JButton backups = new JButton();
        JScrollPane welcomePane = new JScrollPane();
        welcome = new JEditorPane();
        JMenuBar mainMenu = new JMenuBar();
        JMenu menuFile = new JMenu();
        JMenuItem menuAbout = new JMenuItem();
        JMenuItem menuRestart = new JMenuItem();
        JMenuItem menuQuit = new JMenuItem();
        JMenu menuLinks = new JMenu();
        JMenuItem menuGuilded = new JMenuItem();
        JMenuItem menuBuyMeACoffee = new JMenuItem();
        JMenuItem menuSource = new JMenuItem();
        JMenuItem menuWebpage = new JMenuItem();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        addons.setText("Addon Management");
        addons.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                addonsActionPerformed(evt);
            }
        });

        settings.setText("Settings");
        settings.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                settingsActionPerformed(evt);
            }
        });

        backups.setText("Backups");
        backups.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                backupsActionPerformed(evt);
            }
        });

        welcome.setEditable(false);
        welcome.setContentType("text/html"); // NOI18N
        welcomePane.setViewportView(welcome);

        menuFile.setText("Main");

        menuAbout.setText("About");
        menuAbout.setToolTipText("");
        menuAbout.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        menuFile.add(menuAbout);

        menuRestart.setText("Restart");
        menuRestart.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                menuRestartActionPerformed(evt);
            }
        });
        menuFile.add(menuRestart);

        menuQuit.setText("Quit");
        menuQuit.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                menuQuitActionPerformed(evt);
            }
        });
        menuFile.add(menuQuit);

        mainMenu.add(menuFile);

        menuLinks.setText("Links");

        menuGuilded.setText("Guilded: Idrinth's Addons");
        menuGuilded.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                menuGuildedActionPerformed(evt);
            }
        });
        menuLinks.add(menuGuilded);

        menuBuyMeACoffee.setText("BuyMeACoffee");
        menuBuyMeACoffee.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                menuBuyMeACoffeeActionPerformed(evt);
            }
        });
        menuLinks.add(menuBuyMeACoffee);

        menuSource.setText("GitHub: WARAddonClient");
        menuSource.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                menuSourceActionPerformed(evt);
            }
        });
        menuLinks.add(menuSource);

        menuWebpage.setText("Web-Version: Idrinth's Tools");
        menuWebpage.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                menuWebpageActionPerformed(evt);
            }
        });
        menuLinks.add(menuWebpage);

        mainMenu.add(menuLinks);

        setJMenuBar(mainMenu);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addons)
                .addGap(18, 18, 18)
                .addComponent(backups)
                .addGap(18, 18, 18)
                .addComponent(settings)
                .addContainerGap(566, Short.MAX_VALUE))
            .addComponent(welcomePane)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(welcomePane, GroupLayout.PREFERRED_SIZE, 313, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(addons)
                    .addComponent(settings)
                    .addComponent(backups))
                .addGap(0, 86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param evt
     */
    private void menuAboutActionPerformed(ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "This software is provided for free by Björn Büttner.\n"
                + "If you have ideas or bugs please add them to the issues at GitHub:WARAddonClient.\n"
                + "If you want to buy me a coffee you can do so at Buy me a coffee.\n"
                + "If you need support, go to Guilded:Idrinth's Addons", "About", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuAboutActionPerformed

    private void menuSourceActionPerformed(ActionEvent evt) {//GEN-FIRST:event_menuSourceActionPerformed
        try {
            Desktop.getDesktop().browse(new java.net.URI("https://github.com/Idrinth/WARAddonClient/"));
        } catch (URISyntaxException | IOException ex) {
            logger.error(ex);
        }
    }//GEN-LAST:event_menuSourceActionPerformed

    private void menuBuyMeACoffeeActionPerformed(ActionEvent evt) {//GEN-FIRST:event_menuBuyMeACoffeeActionPerformed
        try {
            Desktop.getDesktop().browse(new java.net.URI("https://buymeacoffee.com/idrinth"));
        } catch (URISyntaxException | IOException ex) {
            logger.error(ex);
        }
    }//GEN-LAST:event_menuBuyMeACoffeeActionPerformed

    private void menuGuildedActionPerformed(ActionEvent evt) {//GEN-FIRST:event_menuGuildedActionPerformed
        try {
            Desktop.getDesktop().browse(new java.net.URI("https://guilded.gg/Idrinths-Addons/"));
        } catch (URISyntaxException | IOException ex) {
            logger.error(ex);
        }
    }//GEN-LAST:event_menuGuildedActionPerformed

    private void menuQuitActionPerformed(ActionEvent evt) {//GEN-FIRST:event_menuQuitActionPerformed
        this.dispose();
        Runtime.getRuntime().exit(0);
    }//GEN-LAST:event_menuQuitActionPerformed

    private void menuRestartActionPerformed(ActionEvent evt) {//GEN-FIRST:event_menuRestartActionPerformed
        try {
            restarter.restart();
        } catch (IOException ex) {
            logger.error(ex);
        }
    }//GEN-LAST:event_menuRestartActionPerformed

    private void menuWebpageActionPerformed(ActionEvent evt) {//GEN-FIRST:event_menuWebpageActionPerformed
        try {
            Desktop.getDesktop().browse(new java.net.URI("https://tools.idrinth.de/"));
        } catch (URISyntaxException | IOException ex) {
            logger.error(ex);
        }
    }//GEN-LAST:event_menuWebpageActionPerformed

    private void addonsActionPerformed(ActionEvent evt) {//GEN-FIRST:event_addonsActionPerformed
         map.exchange(MainWindowMap.START, MainWindowMap.ADDONS);
    }//GEN-LAST:event_addonsActionPerformed

    private void settingsActionPerformed(ActionEvent evt) {//GEN-FIRST:event_settingsActionPerformed
        map.exchange(MainWindowMap.START, MainWindowMap.SETTINGS);
    }//GEN-LAST:event_settingsActionPerformed

    private void backupsActionPerformed(ActionEvent evt) {//GEN-FIRST:event_backupsActionPerformed
        map.exchange(MainWindowMap.START, MainWindowMap.BACKUPS);
    }//GEN-LAST:event_backupsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JEditorPane welcome;
    // End of variables declaration//GEN-END:variables
}
